---
title: "Population analysis of *pf*MSP1 in Malaria"
author: "Reuben Yaa"
date: "21/08/2022"
output: github_document
---
## Background
  
Extensive antigenic variability of *Plasmodium falciparum* parasites is known to cause dysregulation of the host immunity during infection and this has been an underlying challenge for antigens that may be clinically protective for vaccine development.  Characterizing polymorphism patterns for these antigens in malaria endemic regions will help in further understanding the host-parasite immune interaction. 

## Analysis
- *Population haplotype analysis*
haplotype clustering and frequencies of their circulation in the population

- *Temporal haplotype density*  
Followed through infection episodes at population level to see how haplotypes change with time

- *Temporal haplotype density*  
  Following individuals through infection episodes and at population level to see how haplotypes change with time and detect the prevalent haplotype with time)

- *Phylogenetic population clustering* 
  How many clusters, Discuss the cluster. Which cluster is common 
<hr>
  
### Reports
  https://mangiruben.github.io/Haplotype-population-analysis-of-pf-MSP1-in-Malaria/code/haplo_freq
  
### [Haplotype frequencies](https://mangiruben.github.io/Haplotype-population-analysis-of-pf-MSP1-in-Malaria/code/haplo_freq)
### [Haplotypes tree and correlations](https://mangiruben.github.io/Haplotype-population-analysis-of-pf-MSP1-in-Malaria/code/haplo_tree_cor)
### [Haplotype distribution across episodes](https://mangiruben.github.io/Haplotype-population-analysis-of-pf-MSP1-in-Malaria/code/hap_distribution)

