---
title: "Haplotypes per patient"
author: "Reuben M. Yaa"
date: "08/11/2022"
output: html_document
---

```{r setup, include=TRUE}
root.dir <- here::here()
knitr::opts_chunk$set(echo = TRUE, root.dir=root.dir)
knitr::opts_knit$set(root.dir = root.dir)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```

## Introduction
Assigned back the haplotypes respective patients irrespective of the infection episodes. This identifies the patients that were mostly infected and by which haplotype. 

### Patients haplotypes distribution
```{r}
library(plotly)
library(dplyr)
library(networkD3)
hap<- readxl::read_xlsx("data/Haplotype assigned.xlsx", col_names = TRUE)
hap <-as.data.frame(hap)
sankey <- function(data, var1, var2, count = "n"){
## Rename
  data$pre_group <- data[[var1]]
  data$group <- data[[var2]]
  ## binding nodes to one object
  group_source <- unique(data$pre_group)
  group_target <- paste0(unique(data$group), " ")
  groups <- c(group_source, group_target)
  nodes_source <- tibble(name = group_source)
  nodes_target <- tibble(name = group_target)
  nodes <- rbind(nodes_source, nodes_target) %>% mutate(node = 0:(nrow(.) - 1))
  
  ## Set up `links`
  links <-
    data %>%
    mutate(group = paste0(group, " ")) %>%
    select(source = "pre_group",
           target = "group",
           value = count)
  
  ## setting up data frame from columns
  nodes_source <- nodes_source %>% select(name) 
  nodes_target <- nodes_target %>% select(name) 
  
  links <-
    links %>%
    mutate(source = as.character(source)) %>% 
    left_join(nodes %>% rename(IDsource = "node"), by = c("source" = "name")) %>%
    left_join(nodes %>% rename(IDtarget = "node"), by = c("target" = "name"))
  
  networkD3::sankeyNetwork(Links = as.data.frame(links),
                           Nodes = as.data.frame(nodes),
                           Source = 'IDsource', 
                           Target = 'IDtarget', 
                           Value = 'value',
                           NodeID = 'name',
                           units="count",
                           fontSize = 14,
                           nodePadding = 7,
                           nodeWidth = 20,
                           sinksRight = FALSE)
}

sankey<-sankey(hap, var1="Patient_ID", var2="Haplotype", count = "Frequency")
sankey
```

### Saving the plot
```{r, results=FALSE}
saveNetwork(sankey, "figures/haplotypes_assigned.html")
png<-webshot::webshot("figures/haplotypes_assigned.html","figures/haplotypes per patient.pdf", vwidth = 1000, vheight = 900)
unlink("figures/haplotypes_assigned*", recursive = TRUE)
```
Figure available [haplotype per patient](https://mangiruben.github.io/pfMSP1-Malaria/figures/haplotypes per patient.pdf)
<hr>
